$('.owl-carousel').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:2500,
    autoplayHoverPause:true,
    margin:10,
    responsive:{
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})